export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_CLASSES = 'FETCH_CLASSES'
export const POST_USER = 'POST_USER'
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS'
export const POST_COURSE_FAILED = 'POST_COURSE_FAILED'
export const POST_SLIDER = 'POST_SLIDER'
export const FETCH_SLIDER = 'FETCH_SLIDER'

// gradebook
export const ADD_GRADEBOOK = 'ADD_GRADEBOOK'
export const ADD_DB_GRADEBOOK_SUCCESS = 'ADD_DB_GRADEBOOK_SUCCESS'
export const ADD_DB_GRADEBOOK_FAILURE = 'ADD_DB_GRADEBOOK_FAILURE'
export const ADD_DB_GRADEBOOK_STARTED = 'ADD_DB_GRADEBOOK_STARTED'
export const REMOVE_GRADEBOOK = 'REMOVE_GRADEBOOK'
export const UPDATE_GRADEBOOK = 'UPDATE_GRADEBOOK'

// assignment
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT'
export const ADD_DB_ASSIGNMENT_STARTED = 'ADD_DB_ASSIGNMENT_STARTED'
export const ADD_DB_ASSIGNMENT_SUCCESS = 'ADD_DB_ASSIGNMENT_SUCCESS'
export const ADD_DB_ASSIGNMENT_FAILURE = 'ADD_DB_ASSIGNMENT_FAILURE'
export const REMOVE_ASSIGNMENT = 'REMOVE_ASSIGNMENT'
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT'

// student
export const ADD_STUDENT = 'ADD_STUDENT'
export const REMOVE_STUDENT = 'REMOVE_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const ADD_DB_STUDENT_SUCCESS = 'ADD_DB_STUDENT_SUCCESS'
export const ADD_DB_STUDENT_FAILURE = 'ADD_DB_STUDENT_FAILURE'
export const ADD_DB_STUDENT_STARTED = 'ADD_DB_STUDENT_STARTED'